import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import Web3 from 'react';
import styles from '../styles/Home.module.css'
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';
import Link from 'next/link';

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <h1 className="text-3xl font-bold">
          体験する
        </h1>

        <div className={styles.grid}>
        <Link href='/experience1'>
          <a className={styles.card}>
            <h2>ケース1: 悪意のあるコントラクト &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </Link>
          <a href="/test" className={styles.card}>
            <h2>ケース2: フロントエンドがハッキングされる &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>
      <Footer />
    </div>

  )
}

export default Home
