import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import Web3 from 'react';
import styles from '../styles/Home.module.css'
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';

const Home: NextPage = () => {

  const [wallet,setWalletAddress] = useState(null)
  
  const connectWallet = async () => {
    // Check if MetaMask is installed on user's browser
    if(window.ethereum) {
      const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
      const chainId = await window.ethereum.request({ method: 'eth_chainId'});
      // Check if user is connected to Ropsten
      if(chainId != '0x3') {
        alert("Please connect to Ropsten");
      }else{
        let wallet = accounts[0];
        setWalletAddress(wallet);
      }
    } else {
      alert("Please install Mask");
    }
    return wallet;
  }

  const sendToken = async () => {
    const Web3 = require('web3');
    const web3 = new Web3(window.ethereum);
    await window.ethereum.enable();
    const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
    let wallet = accounts[0];
    const contract_abi = require('../../abi/BHM_Fauset_abi');
    const contract_address = '0xc2C89adDd9e7549BB1711f845B1A8948fdD74241';
    const Faucet = new web3.eth.Contract(contract_abi, contract_address);
    //const MintContract = new web3.eth.Contract(contract_abi, contract_address);
    await Faucet.methods.send().send({from:wallet});
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <h1 className="text-3xl font-bold">
          まずは体験用トークンを受け取ろう。
        </h1>

        <p className={styles.description}>
          BHMトークンを配布します。<br></br>
          受け取ったトークンでハッキング被害に遭うことができます。
        </p>
        <button onClick={sendToken}>BHMトークンを受け取る</button>
      </main>
      <Footer />
    </div>

  )
}

export default Home
